### ISSUE TITLE
Employee-Payroll-Salary-App-Angular-6-MEAN-Stack (Inability to add employee)

### ISSUE THREAD

**Issue by platinny** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#1]
I downloaded this project, did the necessary thing like installing the database, creating user but i could not add employee because i could not select any option from the drop-downs in the HR* part.

**Comment by AmitXShukla** [comment]
Actually, that's intentional.
You have to first setup a Leave Code, Job Code and Salary Code, which are further used to calculate Employee Salary. Go to Setup > Salary Code, Job Code and Leave Code.
Once you setup these codes (at least one code each), You will be able to add a new employee.

If you do NOT like this design, you can simply change at manage > employeecomponent.html
line # 229, 236, 243, 453, 460 & 467.
For example - 
<mat-select placeholder="Job Code" name="JOB_CODE" id="JOB_CODE" ngModel required>
Remove "required" in above line.

**Comment by platinny** [comment]
That was precisely what I did. I created those codes and it displayed in
the dropdown but when you select any of the defined codes, it won't pick
but only display red job code, salary code and leave code. Let me see what
I can do to it.

**Comment by AmitXShukla** [comment]
Thanks, Please keep me posted, I am going to re-open this issue and will download this repository and run this in my environment again to check.
However, I have my online demo, which seems to be working.
https://elish-erp.firebaseapp.com (HCM Cloud)

If you need more help, please send me your Client>Angular> package.json, employee.component.html and employee.component.ts

**Comment by platinny** [comment]
Okay thanks, i would send them to you soon and also try to check the delete
and edit links because they are not working currently.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by platinny** [comment]
More importantly, you can check what is on your github repo because that
was what i downloaded without any modification.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by platinny** [comment]
I think what you should do is to update the repository with the code you
have in this https://elish-erp.firebaseapp.com becuase i checked it and
everything works there.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by platinny** [comment]
Please get me posted when you fix it so that i can download the updated
code.
I intent to ride on your code as a boilerplate for my new project.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by AmitXShukla** [comment]
I just re-cloned, installed everything and it worked fine.
1. Can you check server side to see if you are able to connect to database as well. and what database you are using.
2. what browser you are using?
I am in LA on Pacific time (10pm-11pm or 9am-11am), if you have webex or skype and show me your system, perhaps I can sort this out.
- Amit

**Comment by platinny** [comment]
Good day to you, I am in Nigeria, GMT +1. I checked the server side and it
seem all is well and i could connect to the DB because i confirmed using
robomongo. My skype id is Ayotunde Ikumawoyi. If you even need to remote in
here using teamviewer, just let me know.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by platinny** [comment]
I just re-installed now and all parts works well.
Thanks for your responses and i am really grateful.
More importantly, i would contact in case i need further clarification on
the code because i am building on what you have done already.

Thanks again.

Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*

**Comment by AmitXShukla** [comment]
Thanks for confirmation, and Good Luck with your project. - Amit

**Comment by platinny** [comment]
Good day to you,
Please I want to replication the "add jobcode" in order to implement my own
add roomcode and i followed these following steps
added the component to setup,
worked on the services/backend,
included it in the route,
added it to the schema,
createed a schema in mongoDB in Model,
Added it to connectors and resolvers,
but i am getting this error when i debug using my browser

   1. [{message: "Cannot query field "room_role" on type "RoomCode". Did
   you mean "job_role"?",…},…]

when it attempts to fetch saved data from the database. I have checked
other things and also confirmed that the data was saved successfully.
Please can you help out on this?
More importantly, i would appreciate it if you can tell me what was
actually wrong in what i did.

Thanks.






Ikumawoyi Ayotunde | platinny10@gmail.com

*Software Developer*

*CELL:* +2348032353494

SKYPE:platinny10

Connect on *Facebook <https://www.facebook.com/Ayotundezekiel>*
