### ISSUE TITLE
I am trying to convert  the sms app from firebase to mongodb but some issue as bad requiets localhost 3000

### ISSUE THREAD

**Issue by haidermlk** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#12]
I am trying to convert  the sms app from firebase to mongodb but some issue as bad requiets localhost 3000
![badreq](https://user-images.githubusercontent.com/44856950/74122804-416a3300-4bee-11ea-89dd-c5eb9428916d.png)

**Comment by AmitXShukla** [comment]
closed, updating this repository to version 11 now.
