### ISSUE TITLE
400 Bad Request - for new component added

### ISSUE THREAD

**Issue by MuthuramanP** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#13]
Hello Sir,
I have gone through your tutorial, It is very nice explanation. Keep it up.
My question is, I have added a new page "Student" and while saving the data it is showing the error like the below...
Error: Http failure response for http://localhost:3000/alivetracking: 400 Bad Request

My Schema:
const studentSchema = new Schema({
    stu_regno: String,
    stu_name: String,
    stu_dob: String,
    stu_mobile: String    
});

**Comment by AmitXShukla** [comment]
https://github.com/AmitXShukla/GPS-Mobile-Tracking-App/issues/2
just open CORS for everything (bad idea) for debugging purpose and see what happens.
app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
