### ISSUE TITLE
not able to signup/create new account

### ISSUE THREAD

**Issue by uzunhayat** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#16]
how to solve it? or what changes should i make?
![payroll](https://user-images.githubusercontent.com/47181793/89730823-dd6edd00-da5f-11ea-9a95-5e4a36c8ee97.jpg)

**Comment by AmitXShukla** [comment]
Can you please include console.log from server, as you can see, your client app is working fine, but is not connecting to server at all. When you click on signup or login, what is response from server? Does it print anything at console, try to add few print logs at client and server both to debug, where is the server not responding,

**Comment by AmitXShukla** [comment]
Also check if your CORS are setup correctly. Please see details here

https://github.com/AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack/issues/2

**Comment by uzunhayat** [comment]
thank you,sir. it works.
