### ISSUE TITLE
How to run the code after updating to angular 11

### ISSUE THREAD

**Issue by Swad197** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#23]
I want to know that after you updated to angular 11 should we run the code same way as shown in the video or something else. Please help me with this issue.

**Comment by AmitXShukla** [comment]
reinstall node, reinstall angular cli,
download this entire repository 
and do a fresh npm install 

follow the instructions on read me file

I'll review and update read me instructions as well (if anything is broken), but i was able to do a fresh npm install at Client/Angular directory and everything compiled without any issues.
