### ISSUE TITLE
nodemon start issue

### ISSUE THREAD

**Issue by Aravind9276** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#24]
Sir how do i solve this mongodb connection error?
[
![server](https://user-images.githubusercontent.com/51526345/100539106-fa6f2c00-3259-11eb-8530-64480647d125.PNG)
](url)

**Comment by Aravind9276** [comment]
Sir also what modules and libraries have you used in the project?

**Comment by AmitXShukla** [comment]
you will find all modules list at Server/package.json

you will have to use and update .env file to your one mongodb database settings.
