### ISSUE TITLE
Mongodb Database

### ISSUE THREAD

**Issue by Aravind9276** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#25]

**Comment by Aravind9276** [comment]
Sir could you explain what went wrong here?
![Mongodb](https://user-images.githubusercontent.com/51526345/100548713-3fb04f80-3294-11eb-8aa2-a57b7611f254.PNG)

**Comment by AmitXShukla** [comment]
sorry i don't know,
and I don't have MongoDb installed to test this.
looks like you are setting up MongoDb user and this mongodb error is saying, there is no such thing as readwrite role,
google MongoDB manuals, I think, there should be some setup/syntax for role setup

**Comment by Aravind9276** [comment]
Thanks sir i got it

**Comment by AmitXShukla** [comment]
Great,
please write your solution to help others .
what you did to fix this error?

Amit

**Comment by Aravind9276** [comment]
It was readWrite sir,not readwrite.The capital W made the difference sir
