### ISSUE TITLE
Update Settings

### ISSUE THREAD

**Issue by Aravind9276** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#28]

**Comment by Aravind9276** [comment]
The update settings part isnt working sir
![update settings](https://user-images.githubusercontent.com/51526345/100613571-c91a5d00-333a-11eb-8da1-5226527ef813.PNG)

**Comment by AmitXShukla** [comment]
did you solve this already ? please share solution if so.

-Amit

**Comment by Aravind9276** [comment]
No sir,it hasnt worked.And im not able to add a new,employee,job code or salary code.Can you help sir

**Comment by AmitXShukla** [comment]
can you please share Angular console log error, also share nodejs /server log 
i think your server may not be setup correctly.

**Comment by Aravind9276** [comment]
Client Side
![Clientside](https://user-images.githubusercontent.com/51526345/100989317-bf7d3900-3576-11eb-935b-02f7aaf0a332.PNG)

**Comment by Aravind9276** [comment]
Server Side
![Serverside](https://user-images.githubusercontent.com/51526345/100989385-d3289f80-3576-11eb-90b8-04a0677ba119.PNG)

**Comment by Aravind9276** [comment]
it keeps loading infinitely when we try to add something sir

**Comment by AmitXShukla** [comment]
what is your PORT setting on server/.env file, At your Server side log, I can see you connect to MongoDB database, which is good.
but your server should say Elish Enterprise Server is ready on localhost: 3000, looks like your node js server is not starting properly. I will download and see if I can reproduce this error on my machine as well. paste your index.js file content here as well.

**Comment by Aravind9276** [comment]
Below is the index.js content sir:
const express = require('express');
const graphqlHTTP = require('express-graphql');
const cors = require('cors');
const app = express();
// store config variables in dotenv
require('dotenv').config();
schema = require('./schema/mongoDBSchema'); // uncomment this for MONGODB
//schema = require('./schema/mysqlDBSchema'); // uncomment this for MYSQL // MYSQL version is not WORKING yet, will update in near future release v1.1.9

// ****** Set up default mongoose connection START ****** //
const mongoose = require('mongoose');
//var mongoDB = process.env.mongoDBMLABURL; // cloud hosted MongoDB
var mongoDB = process.env.mongoDBLocalURL; // locally hosted MongoDB
mongoose.connect(mongoDB);

mongoose.connection.on('error', console.error.bind(console, 'MongoDB connection error:'));
mongoose.connection.once('open', () => {
    console.log('conneted to MONGODB- ElishERP database');
});
// ****** Set up default mongoose connection END ****** //

// ****** allow cross-origin requests code START ****** //
//app.use(cors()); // uncomment this to enable all CORS and delete cors(corsOptions) in below code
var allowedOrigins = process.env.allowedOrigins.split(',');
app.use(cors({
    origin: function (origin, callback) {
        // allow requests with no origin 
        // (like mobile apps or curl requests)
        if (!origin) return callback(null, true);

        if (allowedOrigins.indexOf(origin) === -1) {
            var msg = 'The CORS policy for this site does not ' + 'allow access from the specified Origin.';
            return callback(new Error(msg), false);
        }
        return callback(null, true);
    }
}));
// ****** allow cross-origin requests code END ****** //

// bind express with graphql
app.use('/graphql', graphqlHTTP({
    schema,
    graphiql: false
}));
app.use('/alivetracking', graphqlHTTP({
    schema,
    graphiql: false
}));
app.use('/', (req, res) => res.send("Welcome ElishERP User"));
app.listen(process.env.PORT, () => console.log('Elish Enterprise Server is ready on localhost:' + process.env.GRAPHQLPORT));

**Comment by Aravind9276** [comment]
.env file
![env](https://user-images.githubusercontent.com/51526345/101053021-4baa5300-35ad-11eb-913a-7dfbff4719af.PNG)

**Comment by AmitXShukla** [comment]
in your index.js file, try replacing everything with in this block like this

// ****** allow cross-origin requests code START ****** //
app.use(cors());

// ****** allow cross-origin requests code END ****** //

**Comment by Aravind9276** [comment]
the infinite loading problem isnt going away sir when we try to add new employee,job code,salary code

**Comment by AmitXShukla** [comment]
when you are on loading page, can you please send me browser console.log error

**Comment by Aravind9276** [comment]
I think the issue is with ngIf="dataLoading" sir.It just keeps on loading forever

**Comment by AmitXShukla** [comment]
spinner is not the issue, fact is, not fetching data. can you share console log from browser and paste a complete pic of the page.

**Comment by sanjayrane** [comment]
> Client Side
> ![Clientside](https://user-images.githubusercontent.com/51526345/100989317-bf7d3900-3576-11eb-935b-02f7aaf0a332.PNG)

add angular.json
  "allowedCommonJsDependencies": [
              "lodash", --like             
            ],

**Comment by AmitXShukla** [comment]
Thanks Sanjay,
is this something I should update to in this repo?

Amit
