### ISSUE TITLE
 name: 'MongoNetworkError',  message:    'failed to connect to server [xyxyxy.mlab.com:20208] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND xyxyxy.mlab.com xyxyxy.mlab.com:20208]',   errorLabels: [ 'TransientTransactionError' ],  [Symbol(mongoErrorContextSymbol)]: {} }

### ISSUE THREAD

**Issue by sanuvish11** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#4]
name: 'MongoNetworkError',  message:
   'failed to connect to server [xyxyxy.mlab.com:20208] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND xyxyxy.mlab.com xyxyxy.mlab.com:20208]',
  errorLabels: [ 'TransientTransactionError' ],  [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by AmitXShukla** [comment]
closed, updating this repository to version 11 now.

**Comment by sanuvish11** [comment]
Salve this issue

**Comment by AmitXShukla** [comment]
> Salve this issue

I assume, you are saying, you solved this issue already and not, you want me to solve it instead.
