### ISSUE TITLE
Not able to run angular app

### ISSUE THREAD

**Issue by vaidyashubham** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#6]
I have established a  connection with mongoDB but unable to run the angular app.

**Comment by AmitXShukla** [comment]
Can you please send me error (attach details/screen shots here)

**Comment by vaidyashubham** [comment]
Thanks for your reply. My system was not able to install the npm package thats why it comes. Now i fixed it.
Thanks for the this project.
