### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by nik5233** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#7]
I can't load any icons form cloned project

![Screenshot](https://user-images.githubusercontent.com/33506885/60537918-2f0a4b80-9d27-11e9-9ef9-0815c3e066e3.png)

**Comment by AmitXShukla** [comment]
Can you please download and make sure Angular -> src -> assets/icons directory has all of these icons.
This is the link to icons you can download from.
https://github.com/AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack/tree/master/Client/Angular/src/assets/icons
