### ISSUE TITLE
not connecting to server

### ISSUE THREAD

**Issue by abhichangela** [AmitXShukla/Employee-Payroll-Salary-App-Angular-6-MEAN-Stack#8]
please help me for error
![payroll1](https://user-images.githubusercontent.com/22442250/64096408-35489280-cd7f-11e9-9a4a-50378254ba95.PNG)

**Comment by ajewole2019** [comment]
Simply do npm install

**Comment by AmitXShukla** [comment]
closed, updating this repository to version 11 now.
